---
- name: Setup Minecraft Server on EC2
  hosts: minecraft
  become: yes

  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - openjdk-21-jre-headless
        - screen
        - wget
        - ca-certificates
        - curl
        - gnupg
        - lsb-release

    - name: Add Docker GPG key
      shell: |
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        chmod a+r /etc/apt/keyrings/docker.gpg

    - name: Add Docker repository
      shell: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        update_cache: yes
        state: present

    - name: Enable Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Create Minecraft directory
      file:
        path: /home/ubuntu/minecraft_server
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: 0755

    - name: Create docker-compose.yml
      copy:
        dest: /home/ubuntu/minecraft_server/docker-compose.yml
        content: |
          services:
            mc:
              image: itzg/minecraft-server
              tty: true
              stdin_open: true
              ports:
                - "25565:25565"
              environment:
                EULA: "TRUE"
              volumes:
                - ./data:/data
              restart: unless-stopped

    - name: Run Minecraft server
      shell: docker compose up -d
      args:
        chdir: /home/ubuntu/minecraft_server
