---
- name: Setup Minecraft Docker Server
  hosts: minecraft
  become: true

  tasks:
    - name: Update apt and install prerequisites
      apt:
        update_cache: yes
        name: [curl, ca-certificates, gnupg, lsb-release]
        state: present

    - name: Upload docker-setup.sh
      copy:
        src: files/docker-setup.sh
        dest: /home/ubuntu/docker-setup.sh
        mode: '0755'

    - name: Run docker-setup.sh
      shell: ./docker-setup.sh
      args:
        chdir: /home/ubuntu

    - name: Upload docker-compose.yml
      copy:
        src: files/docker-compose.yml
        dest: /home/ubuntu/docker-compose.yml

    - name: Upload run-script.sh
      copy:
        src: files/run-script.sh
        dest: /home/ubuntu/run-script.sh
        mode: '0755'

    - name: Run run-script.sh
      shell: ./run-script.sh
      args:
        chdir: /home/ubuntu
